### ISSUE TITLE
add support for mtk phones 

### ISSUE THREAD

**Issue by dananothername** [edk2-porting/edk2-msm#200]
### Prerequisites

* [x] Have you read the wiki?
* [ ] Is your device in the supported list?
* [ ] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by halal-beef** [comment]
Never :trollface:

**Comment by gus33000** [comment]
![image](https://user-images.githubusercontent.com/3755345/205512764-93663da4-7bd8-47e4-8dac-6314401987b6.png)

not msm :)
