### ISSUE TITLE
Oneplus 6t recovery 

### ISSUE THREAD

**Issue by Momoprawdziwe** [edk2-porting/edk2-msm#216]
![IMG_20221230_095901](https://user-images.githubusercontent.com/103530767/210134558-4771bf42-17fb-4e48-acba-e4afc2961f81.jpg)
### Prerequisites

* [x] Have you read the wiki?
* [x] Is your device in the supported list?
* [x] Does the device have a Snapdragon SOC which is supported in this repo?

### Description
Device can't boot I installed drivers with modified 850inf

**Comment by TheMorc** [comment]
https://renegade-project.tech/en/install#h-44-your-pcdevice-needs-to-be-repaired

**Comment by TheMorc** [comment]
What guide did you use and where did you get drivers from?

**Comment by Momoprawdziwe** [comment]
https://youtu.be/CaQ9B6IGIjg 
This is guide I was using

**Comment by TheMorc** [comment]
> https://youtu.be/CaQ9B6IGIjg
> This is guide I was using

Uh, we don’t provide any support for YouTube tutorials since they are bound to get outdated quickly as the project moves on.
