### ISSUE TITLE
realme x2 pro - stuck at realme logo

### ISSUE THREAD

**Issue by cncnote** [edk2-porting/edk2-msm#217]
### Prerequisites

* [ yes] Have you read the wiki?
* [no ] Is your device in the supported list?
* [ yes] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

After reading the porting guide carefully and building uefi.img it doesn't boot and stuck at realme logo.

**Expected behavior:** It boots to UEFI boot menu

**Actual behavior:** Stuck at realme logo

**Comment by qaz6750** [comment]
- Check whether the DTB is correct

- Check whether the Display Reserved address is correct
