### ISSUE TITLE
[Request] Port for Mi 11 Lite 4G 732G (SM7150)

### ISSUE THREAD

**Issue by ask9027** [edk2-porting/edk2-msm#222]
### Prerequisites

* [X] Have you read the wiki?
* [ ] Is your device in the supported list?
* [X] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

Since Redmi note 10 pro and Mi 11 Lite 4G have same CPU Config.
Both have SM7150( Snapdragon 732G)
Please make port for Mi 11 Lite 4G (Board : courbetin or courbet)

Here is the Details of CPU.
![Screenshot_2023-01-08-11-34-38-189-edit_com ytheekshana deviceinfo](https://user-images.githubusercontent.com/61283438/211183064-4b171a11-2917-4b8f-b017-812586d788b0.jpg)

**Comment by qaz6750** [comment]
You should know： 
- Developers don't have so much time, and debugging without devices is extremely difficult
- Since it is the same soc, you can try to transplant it yourself

**Comment by ask9027** [comment]
Okay, i will try myself. Thanks
