### ISSUE TITLE
呃我能往msm8953 骁龙625上面移植吗？ Can I port this projcet on msm89s53

### ISSUE THREAD

**Issue by bzy-080408** [edk2-porting/edk2-msm#224]
已知的EFIDroid有人往msm8953上面移植，但是那个项目几乎停止更新了
我手机：华为nova plus
lk2nd我移植了，（但是不好用

**Comment by qaz6750** [comment]
- 经过研究，msm8953属于aarch64处理器，这说明也许不需要更改太多
- 你可以从xbl分区获取一些文件以完成移植，同时检查是否拥有abl分区，以检查是否与821一样，如果不含有ABL只有xbl，那么也许移植更加的不容易
- 欢迎贡献
- ━(*｀∀´*)ノ亻!

**Comment by qaz6750** [comment]
- Please also follow the relevant agreements of the project

**Comment by bzy-080408** [comment]
额但是msm8953是由SBL1直接引导emmc_appsboot启动的，似乎没有abl和xbl分区

**Comment by qaz6750** [comment]
- 也许只能适配arm32位的uefi,因为没有xbl，适配将会很可能，而且本库属于aarch64,可能要改动比较大，我建议去参考Lumia930的arm32并且按照你设备的配置进行修改

**Comment by bzy-080408** [comment]
花说EFIDroid是怎么弄的。。。我自己编译那个项目编译不过，似乎是编译器问题。。。
同CPU的设备有人写了EFIDroid的配置，但是似乎都没跑起来
