### ISSUE TITLE
could you support more devices ?

### ISSUE THREAD

**Issue by superiums** [edk2-porting/edk2-msm#230]
### Prerequisites

* [ Y ] Have you read the wiki?
* [ N ] Is your device in the supported list?
* [ N ] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

[support more devices]

really Great Project!

i'm on motorola edge s (nio).
This is the [kernel code](https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRN31.Q1-20-52-3)
This is the [device information](https://wiki.lineageos.org/devices/nio/)

**Comment by qaz6750** [comment]
- I suggest you try your own transplantation

**Comment by MollySophia** [comment]
Actually the more devices this project supports, the harder it is to be maintained. The reason is that there are not enough developers, and developers cannot own that many devices to port and test with convenience.
BTW Snapdragon 865/870 really doesn't have much support now :P

**Comment by superiums** [comment]
> * I suggest you try your own transplantation

is there any guid document ?

**Comment by qaz6750** [comment]
> > * I suggest you try your own transplantation
> 
> is there any guid document ?

* https://renegade-project.tech/en/porting/device
