### ISSUE TITLE
can i make this work for Lenovo Miix 630 (snapdragon 835)?

### ISSUE THREAD

**Issue by Titoot** [edk2-porting/edk2-msm#239]
### Prerequisites

* [x] Have you read the wiki?
* [ ] Is your device in the supported list?
* [x] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

is there's a way to make this work on Lenovo Miix 630, it has snapdragon 835, and it had windows 10 1709 installed before, but i'm unable to reinstall it again

**Comment by MollySophia** [comment]
AFAIK  Lenovo Miix 630 has native Windows support and I don't really see the point of trying to port this project to that instead of using the native support :P
You can try working on that though
