### ISSUE TITLE
MacOS available on Mi8 (dipper)?

### ISSUE THREAD

**Issue by uufukyucel** [edk2-porting/edk2-msm#242]
### Prerequisites

* [ yes] Have you read the wiki?
* [ yes] Is your device in the supported list?
* [ yes] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

[Description of the bug or feature]

**Expected behavior:** Hello, can i install macos? I mean hackintosh.

**Actual behavior:** [What actually happened]

**Comment by PhucHauDeveloper** [comment]
Never bro, only intel and amd with x64
