### ISSUE TITLE
edk3e

### ISSUE THREAD

**Issue by Linuxwl** [edk2-porting/edk2-msm#284]

**Comment by ungeskriptet** [comment]
I'm sorry to disappoint you, but edk3 doesn't exist yet.

**Comment by leandrofriedrich** [comment]
How do you know? @ungeskriptet

**Comment by J0SH1X** [comment]
Stop the trolling, NOW.

We're not in kindergarten.

Leandro Friedrich ***@***.***> schrieb am Di., 28. März 2023,
08:29:
