### ISSUE TITLE
Platform: Add xiaomi redmi k20pro (raphael) (sm8150) support

### ISSUE THREAD

**Issue by 54pkp** [edk2-porting/edk2-msm#314]
### Prerequisites

* [ Y ] Have you read the wiki?
* [ Y ] Is your device in the supported list?
* [ Y ] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

Please add xiaomi redmi k20pro (raphael) support and add the device (raphael) to Actions.

**Comment by Fuzy35** [comment]
Any news ?

**Comment by graphiks** [comment]
just use msmnilepkg
