### ISSUE TITLE
I'm masturbating on Snapdragon 855

### ISSUE THREAD

**Issue by pidorkalobrod** [edk2-porting/edk2-msm#323]
What i should do?

**Comment by TheBACKTRACK** [comment]
@pidorkalobrod Maybe... You should stop?

**Comment by SnowFuhrer** [comment]
@pidorkalobrod :|

**Comment by TheBACKTRACK** [comment]
@SnowFuhrer Пидор калоброд

**Comment by halal-beef** [comment]
so real!

**Comment by TheBACKTRACK** [comment]
I think you should stop now

**Comment by mrksbgg** [comment]
Dont stop

**Comment by halal-beef** [comment]
forbidden thermal paste

**Comment by mrksbgg** [comment]
> forbidden thermal paste

thermal paste for ryzen 9

**Comment by TheBACKTRACK** [comment]
Best thermal paste for Intel Core i5 10300H

**Comment by J0SH1X** [comment]
@mrksbgg never eat halal its bad

**Comment by halal-beef** [comment]
> @mrksbgg never eat halal its bad

whatever u say bruder

**Comment by J0SH1X** [comment]
@J0SH1X doner kebab is mostly from halal meet

**Comment by mrksbgg** [comment]
> @mrksbgg never eat halal its bad

why halal is bad

**Comment by J0SH1X** [comment]
@mrksbgg he will port edk2 to your brain

**Comment by halal-beef** [comment]
> @J0SH1X doner kebab is mostly from halal meet

doner good men

**Comment by halal-beef** [comment]
u have unlimited turkey people too so infinite doner

**Comment by halal-beef** [comment]
> What i should do?

is it done

**Comment by halal-beef** [comment]
or are u still going

**Comment by nedokaka** [comment]
@pidorkalobrod ok
