### ISSUE TITLE
MediaTek Dimensity 9000 Windows 11 support please

### ISSUE THREAD

**Issue by TheBACKTRACK** [edk2-porting/edk2-msm#324]
### Prerequisites

* [N] Have you read the wiki?
* [I think yes] Is your device in the supported list?
* [N, please MediaTek] Does the device have a Snapdragon SOC which is supported in this repo?

Please Windows 11 for MediaTek Dimensity 9000, i hope it has best Windows support ever

**Comment by TheBACKTRACK** [comment]
@TheBACKTRACK Windows Rockhip please

**Comment by qcomnile** [comment]
@TheBACKTRACK it has gayest support ever

**Comment by govnoed1488dorogayayakupiltebehuinu911** [comment]
I support porn for ur device with dimensity 9000 rockchip edition pro max ultra big black cock edition
