### ISSUE TITLE
MediaTek Dimensity 8050 port UEFI and Windows please

### ISSUE THREAD

**Issue by pidorgandon69** [edk2-porting/edk2-msm#326]
I want Windows port for Tecno Camon 20 Pro 5G. I really want to play GTA 5 on my phone. MediaTek Dimensity 8050 have more performance than, for example, Ryzen 9 5900X.
So i will get 1000+ FPS in GTA 5
I think it has very good support of Windows
And also, this CPU can use ARM and x86 because i can play Half Life 2 in Android
HL2 is x86 game, so, this CPU can switch to x86
I think that porting Windows to this CPU will be very easy because this CPU can switch to x86 from ARM 
I can help because i'm expert in Ubuntu, for example, not so many people know about Nano text editor. And also, switching to other desktop environment is very hard
But i don't know anything about Arch Linux because Arch is hardest Linux distro

**Comment by nedokaka** [comment]
@pidorgandon69 idi nahui

**Comment by TheBACKTRACK** [comment]
@pidorgandon69 Ты еблан?

**Comment by govnoed1488dorogayayakupiltebehuinu911** [comment]
Почему я не могу просто взять и выйти на площадь голым и начать портировать винду на деменцию 8050. А после насиловать всех прохожих в анальное отверстие и обмазывать их фекалиями. После помочится на прохожих при этом повторяя "Хуй каки, каки париром пом, пом". Потом через минуту вернутся домой, взять с собой швабру и сметану, вернутся на площадь, раздеть прохожего и обмазать его анус сметаной после засунуть в него шваброй и начать его насиловать. Потом через полчаса засунуть швабру так глубоко, что она вылезет у него из рта, и когда он задохнётся вынуть её всю в фекалиях, поднять вверх и закричать: "Я викинг могучего хуя властилина!" и избивать насмерть всех прохожих. А, через полчаса справить нужду по большому в банку сметаны и зайти в ближайшее кафе с криками "Я джедай пизды негра! Пришёл сюда смазать очко сучкам!" и кидаться содержимым в банке в людей и их насиловать. После украсть в супермаркете масло, угнать чей-то велосипед и катаясь по площади обливать всех маслом крича "Вы все вафлёры, а я бог солнца" . Когда масло закончится, крикнуть "Сочные сиськи" и набросится на ближайшего человека и насиловать его до конца дня.

**Comment by ETCHDEV** [comment]
What are you talking about, even I know about nano and more. No, it doesn't support x86 and half life 2 is ported for arm

**Comment by muhammad23012009** [comment]
@pidorgandon69 nice bro, good luck

**Comment by vladimirlishchuk** [comment]
lmao
