### ISSUE TITLE
Windus 7 port on hisilicon when?

### ISSUE THREAD

**Issue by govnoed1488dorogayayakupiltebehuinu911** [edk2-porting/edk2-msm#329]
### Prerequisites

* [N] Have you read the wiki?
* [N] Is your device in the supported list?
* [N] Does the device have a Snapdragon SOC which is supported in this repo?

On edk2's github i found [hisilicon](https://github.com/tianocore/edk2-platforms/tree/master/Silicon/Hisilicon) mention and i'm indus, 
so when port on hauwei?

**Comment by halal-beef** [comment]
Yes
