### ISSUE TITLE
I have a finger cancer. So, i want to port EDK2 to my finger

### ISSUE THREAD

**Issue by dagestansheep** [edk2-porting/edk2-msm#336]
(https://github.com/edk2-porting/edk2-msm/assets/143660982/bbede1fc-80b4-4661-ab09-da48756b6219)

**Comment by halal-beef** [comment]
@dagestansheep Real

**Comment by SnowFuhrer** [comment]
@dagestansheep What the 😭

**Comment by hiprivsid** [comment]
@dagestansheep fuck you

**Comment by J0SH1X** [comment]
@dagestansheep Wen eta volte for finger pls sir
