### ISSUE TITLE
I like to fuck Dagestan sheeps

### ISSUE THREAD

**Issue by dagestansheep** [edk2-porting/edk2-msm#337]
Pls port EDK2 to Dagestan sheep, it has RockChip

**Comment by halal-beef** [comment]
Which rockchip

**Comment by leandrofriedrich** [comment]
@dagestansheep Sorry, edk2 no support dagestan, try edeka3 for dagestan

**Comment by halal-beef** [comment]
@leandrofriedrich Shut up lindro

**Comment by hiprivsid** [comment]
@leandrofriedrich why not edk2-dagestan from Abdul?

**Comment by halal-beef** [comment]
@hiprivsid Cause they denied PR
