### ISSUE TITLE
how to flash custom Emi thankyou🙏🙏🙏

### ISSUE THREAD

**Issue by anuspuk** [edk2-porting/edk2-msm#340]
https://github.com/edk2-porting/edk2-msm/assets/143949373/356a5653-83d6-4235-832f-e37d6bb53421

**Comment by TheBACKTRACK** [comment]
@anuspuk how to flash custom Emi thankyou🙏🙏🙏

**Comment by halal-beef** [comment]
@anuspuk Fuck off

**Comment by hiprivsid** [comment]
@anuspuk erase abl
