### ISSUE TITLE
Acpi tables

### ISSUE THREAD

**Issue by Easonqsp** [edk2-porting/edk2-msm#345]
### Prerequisites

* [* ] Have you read the wiki?
* [* ] Is your device in the supported list?
* [* ] Does the device have a Snapdragon SOC which is supported in this repo?

I'm wondering how to get acpi tables for Xiaomi odin based on sm8350

**Comment by gus33000** [comment]
You cant, android devices ship without ACPI tables. They have to be remade from scratch or adapted from other SoCs
