### ISSUE TITLE
building got error

### ISSUE THREAD

**Issue by HAKODEVx** [edk2-porting/edk2-msm#348]
### Prerequisites

* [Yes] Have you read the wiki?
* [Xiaomi Redmi Note 12] Is your device in the supported list?
* [ SM6225-AD With Modify for forked SM6225] Does the device have a Snapdragon SOC which is supported in this repo?

### Description
building got error SimpleFileSystem.h unmodify

[Description of the bug or feature]
SimpleFileSystem.h (unmodiy)

**Expected behavior:** [What you expected to happen]
Attacked file log
[log.txt](https://github.com/edk2-porting/edk2-msm/files/12672335/log.txt)

**Actual behavior:** [What actually happened]
idk

**Comment by qaz6750** [comment]
* Please compile using WSl2 or ext4 (Linux environment) instead of placing it in Windows
