### ISSUE TITLE
black screen after booting compiled uefi image

### ISSUE THREAD

**Issue by softai** [edk2-porting/edk2-msm#358]
Hello

I have a xiomi 11t pro snapdragon 888 sm8350, I try to build the uefi image using the deice "q2q" that has the same chip as mine. Also with the surface 2 but both give me a black screen after "fastboot boot boot-q2q.img" command.

Should it show something on the screen at least? 

Note: My phone is unlocked, TWRP and rooted (magisk) with last OEM updates.

My current goal is to show something on the screen first.

**Comment by halal-beef** [comment]
@softai U need to port ur own device
