### ISSUE TITLE
Xiaomi Mi A1

### ISSUE THREAD

**Issue by MuhammedEmirArtan** [edk2-porting/edk2-msm#377]
### Prerequisites

* [ yes] Have you read the wiki?
* [no ] Is your device in the supported list?
* [qualcomm snapdragon 625 and i think yes] Does the device have a Snapdragon SOC which is supported in this repo?

### Description
so when you will add support for the mi a1?
[Description of the bug or feature]
i want to install win 10 / 11 
**Expected behavior:** [What you expected to happen]
seeing mi a1 on the supported devices list
**Actual behavior:** [What actually happened]
no

**Comment by rxuglr** [comment]
@MuhammedEmirArtan What

**Comment by MuhammedEmirArtan** [comment]
@rxuglr umm yes

**Comment by NetuserPRO** [comment]
@MuhammedEmirArtan add it yourself

**Comment by MuhammedEmirArtan** [comment]
@NetuserPRO do you mean porting

**Comment by rxuglr** [comment]
@MuhammedEmirArtan Yup

**Comment by NetuserPRO** [comment]
@MuhammedEmirArtan yes ofc, and windows on 625 doesn't have drivers

**Comment by MuhammedEmirArtan** [comment]
so it will not work

**Comment by NetuserPRO** [comment]
@MuhammedEmirArtan it CAN work, just don't expect much

**Comment by MuhammedEmirArtan** [comment]
hmmm
so am i have to do anything additional with the normal installation or porting

**Comment by MuhammedEmirArtan** [comment]
https://xdaforums.com/t/driver-adreno-5xx-gpu-driver-v313-rev23-v331-rev1.3815853/
@NetuserPRO

**Comment by MuhammedEmirArtan** [comment]
oh wait

**Comment by MuhammedEmirArtan** [comment]
this is an android driver :skull:

**Comment by NetuserPRO** [comment]
@MuhammedEmirArtan porting, a lot of porting.

**Comment by MuhammedEmirArtan** [comment]
hmm so i have to rewrite CPU driver 
can i do it with a template

**Comment by NetuserPRO** [comment]
@MuhammedEmirArtan figure it out yourself

**Comment by MuhammedEmirArtan** [comment]
nah i give up
