### ISSUE TITLE
Add support for LG V30 (joan) msm8998

### ISSUE THREAD

**Issue by bronnel** [edk2-porting/edk2-msm#395]
### Prerequisites

* [yes ] Have you read the wiki?
* [no ] Is your device in the supported list?
* [no ] Does the device have a Snapdragon SOC which is supported in this repo?

### Description
add  support for LG V30 (joan) msm8998 , it has snapdragon 835

**Comment by Daniel224455** [comment]
dude port it yourself

**Comment by J0SH1X** [comment]
Port it then

**Comment by bronnel** [comment]
> Port it then

is there a guide to port it?

**Comment by bronnel** [comment]
> dude port it yourself

guide ?
