### ISSUE TITLE
How to solve this problem Oneplus 5t

### ISSUE THREAD

**Issue by Ok12340** [edk2-porting/edk2-msm#398]
How can I fix this? I tried to create a boot.img file for Oneplus 5t but this error always occurs.
![IMG_20240620_174054](https://github.com/edk2-porting/edk2-msm/assets/167163863/72ad5273-44bb-4672-9944-391f89a63aa4)

**Comment by gus33000** [comment]
Looks like you are on ubuntu so:

`sudo apt-get -y install abootimg`
