### ISSUE TITLE
Francisco 

### ISSUE THREAD

**Issue by franellargo2** [edk2-porting/edk2-msm#399]
### Prerequisites

* [ ] Have you read the wiki?
* [ ] Is your device in the supported list?
* [ ] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by franellargo2** [comment]
.

**Comment by Icesito68** [comment]
Don't give me so much information, I feel nervous

**Comment by ASDownloadingAccount** [comment]
Can anyone even delete this? I'm sorry if it was reopened automatically, but I'll close it now.
