### ISSUE TITLE
abootimg: 未找到命令

### ISSUE THREAD

**Issue by SKY-winlight** [edk2-porting/edk2-msm#403]
![Screenshot_20240907_080909.jpg](https://github.com/user-attachments/assets/3fceb1d0-0d3e-4a08-a386-9ff59a7be21d)

660好像都会这样，不知道怎么回事

**Comment by qaz6750** [comment]
请检查是否安装abootimg相关软件包

**Comment by SKY-winlight** [comment]
> 请检查是否安装abootimg相关软件包

感谢提示，成功解决![Screenshot_20240907_141214.jpg](https://github.com/user-attachments/assets/dd72900f-471a-4282-b8f4-84f88d730e5d)
