### ISSUE TITLE
Can i build it for Google Pixel 4a?

### ISSUE THREAD

**Issue by SystemTraveler** [edk2-porting/edk2-msm#404]
### Prerequisites

* [ Yes ] Have you read the wiki?
* [ No ] Is your device in the supported list?
* [ Yes ] Does the device have a Snapdragon SOC which is supported in this repo?

### Description

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by Daniel224455** [comment]
yes but don't expect windows to boot, itll nuke your ufs

**Comment by graphiks** [comment]
@SystemTraveler no, it will blow up

**Comment by Daniel224455** [comment]
https://github.com/user-attachments/assets/1a4a7e19-abf9-408e-8e10-3984a2ce4354

**Comment by SystemTraveler** [comment]
> да, но не ждите, что Windows загрузится, это уничтожит ваш UFS

(((
