### ISSUE TITLE
The clone EDK2-MSM process appears that command 305 is not found

### ISSUE THREAD

**Issue by SKY-winlight** [edk2-porting/edk2-msm#406]
Read the wiki
================
The previous clone was normal, but the clone recently did not find command 305, and multiple clones could not solve the problem.

**Comment by gus33000** [comment]
Hi can you be a bit more explicit and give more info, the whole issue you created makes absolutely no sense to me, sorry :/

**Comment by SKY-winlight** [comment]
> 嗨，你能不能更明确一点并提供更多信息，你创建的整个问题对我来说完全没有意义，对不起 ：/
I think the problem has been solved, the cause is on my ubuntu package dependency, there were other packages that overwrote the correct package, I apologize if you bothered you about the creation of this issue.
