### ISSUE TITLE
pls support exynos phones

### ISSUE THREAD

**Issue by moha0116** [edk2-porting/edk2-msm#98]
pls support exynos 850
i have samsung a12 pls support it
this device is not in suported device list
pls support it

**Comment by TAOcroatia** [comment]
No

**Comment by Sota4Ever** [comment]
Yes, I'm waiting for them to specifically put Exynos 990 Samsung S20 FE 4g processors

**Comment by NetuserPRO** [comment]
@Sota4Ever please read the repository name

**Comment by J0SH1X** [comment]
Closing this bullshit

**Comment by J0SH1X** [comment]
Wont fix
